# Generated by Django 5.2.5 on 2025-08-17 22:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.CharField(error_messages={'unique': 'Cette raison sociale est déjà utilisée.'}, help_text='Nom ou raison sociale du bénéficiaire', max_length=100, unique=True, verbose_name='Raison sociale')),
                ('adresse', models.CharField(blank=True, help_text='Adresse du bénéficiaire', max_length=50, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, help_text='Ville', max_length=20, null=True, verbose_name='Ville')),
                ('telephone', models.CharField(blank=True, error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé.'}, help_text='Numéro de téléphone', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir exactement 10 chiffres.', regex='^\\d{10}$')], verbose_name='Téléphone')),
                ('registre_commerce', models.CharField(error_messages={'unique': 'Ce registre du commerce est déjà utilisé.'}, help_text='Numéro de registre du commerce', max_length=20, unique=True, verbose_name='Registre du commerce')),
                ('identifiant_fiscale', models.CharField(error_messages={'unique': 'Cet identifiant fiscal est déjà utilisé.'}, help_text='Identifiant fiscal du bénéficiaire', max_length=20, unique=True, verbose_name='Identifiant fiscal')),
                ('code_ice', models.CharField(error_messages={'unique': 'Ce code ICE est déjà utilisé.'}, help_text="Identifiant Commun de l'Entreprise (ICE)", max_length=15, unique=True, verbose_name='Code ICE')),
                ('actif', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['raison_sociale'],
            },
        ),
    ]
